/**
 * Match free-form country values (names, common variants, ISO codes) against
 * the Natural Earth feature names shipped in world-atlas.
 */

export function normalizeCountryKey(raw: string): string {
  return raw
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '');
}

/**
 * Normalized alias → normalized Natural Earth name (110m atlas spelling).
 * Covers common BI spellings plus ISO 3166 alpha-2/alpha-3 codes.
 */
const COUNTRY_ALIASES: Record<string, string> = {
  // United States
  us: 'unitedstatesofamerica',
  usa: 'unitedstatesofamerica',
  unitedstates: 'unitedstatesofamerica',
  america: 'unitedstatesofamerica',
  // United Kingdom
  uk: 'unitedkingdom',
  gb: 'unitedkingdom',
  gbr: 'unitedkingdom',
  greatbritain: 'unitedkingdom',
  britain: 'unitedkingdom',
  england: 'unitedkingdom',
  // Abbreviated Natural Earth names
  democraticrepublicofthecongo: 'demrepcongo',
  drcongo: 'demrepcongo',
  drc: 'demrepcongo',
  congokinshasa: 'demrepcongo',
  cod: 'demrepcongo',
  republicofthecongo: 'congo',
  congobrazzaville: 'congo',
  cog: 'congo',
  bosnia: 'bosniaandherz',
  bosniaandherzegovina: 'bosniaandherz',
  bih: 'bosniaandherz',
  centralafricanrepublic: 'centralafricanrep',
  caf: 'centralafricanrep',
  dominicanrepublic: 'dominicanrep',
  dom: 'dominicanrep',
  equatorialguinea: 'eqguinea',
  gnq: 'eqguinea',
  southsudan: 'ssudan',
  ssd: 'ssudan',
  westernsahara: 'wsahara',
  esh: 'wsahara',
  solomonislands: 'solomonis',
  slb: 'solomonis',
  falklandislands: 'falklandis',
  flk: 'falklandis',
  northerncyprus: 'ncyprus',
  ivorycoast: 'cotedivoire',
  civ: 'cotedivoire',
  // Renames / official long forms
  czechrepublic: 'czechia',
  cze: 'czechia',
  burma: 'myanmar',
  mmr: 'myanmar',
  swaziland: 'eswatini',
  swz: 'eswatini',
  easttimor: 'timorleste',
  tls: 'timorleste',
  northmacedonia: 'macedonia',
  mkd: 'macedonia',
  turkiye: 'turkey',
  russianfederation: 'russia',
  republicofkorea: 'southkorea',
  korea: 'southkorea',
  kor: 'southkorea',
  democraticpeoplesrepublicofkorea: 'northkorea',
  dprk: 'northkorea',
  prk: 'northkorea',
  vietnam: 'vietnam',
  socialistrepublicofvietnam: 'vietnam',
  laopeoplesdemocraticrepublic: 'laos',
  syrianarabrepublic: 'syria',
  islamicrepublicofiran: 'iran',
  uae: 'unitedarabemirates',
  are: 'unitedarabemirates',
  // ISO codes for frequent BI countries (alpha-2 and alpha-3)
  de: 'germany',
  deu: 'germany',
  fr: 'france',
  fra: 'france',
  jp: 'japan',
  jpn: 'japan',
  cn: 'china',
  chn: 'china',
  in: 'india',
  ind: 'india',
  br: 'brazil',
  bra: 'brazil',
  mx: 'mexico',
  mex: 'mexico',
  ca: 'canada',
  can: 'canada',
  au: 'australia',
  aus: 'australia',
  es: 'spain',
  esp: 'spain',
  it: 'italy',
  ita: 'italy',
  nl: 'netherlands',
  nld: 'netherlands',
  se: 'sweden',
  swe: 'sweden',
  no: 'norway',
  nor: 'norway',
  dk: 'denmark',
  dnk: 'denmark',
  fi: 'finland',
  fin: 'finland',
  pl: 'poland',
  pol: 'poland',
  pt: 'portugal',
  prt: 'portugal',
  gr: 'greece',
  grc: 'greece',
  che: 'switzerland',
  at: 'austria',
  aut: 'austria',
  be: 'belgium',
  bel: 'belgium',
  ie: 'ireland',
  irl: 'ireland',
  nz: 'newzealand',
  nzl: 'newzealand',
  za: 'southafrica',
  zaf: 'southafrica',
  ng: 'nigeria',
  nga: 'nigeria',
  eg: 'egypt',
  egy: 'egypt',
  ke: 'kenya',
  ken: 'kenya',
  et: 'ethiopia',
  eth: 'ethiopia',
  gh: 'ghana',
  gha: 'ghana',
  ma: 'morocco',
  mar: 'morocco',
  dz: 'algeria',
  dza: 'algeria',
  tz: 'tanzania',
  tza: 'tanzania',
  ug: 'uganda',
  uga: 'uganda',
  rw: 'rwanda',
  rwa: 'rwanda',
  sn: 'senegal',
  sen: 'senegal',
  cm: 'cameroon',
  cmr: 'cameroon',
  zm: 'zambia',
  zmb: 'zambia',
  zw: 'zimbabwe',
  zwe: 'zimbabwe',
  mz: 'mozambique',
  moz: 'mozambique',
  ao: 'angola',
  ago: 'angola',
  sd: 'sudan',
  sdn: 'sudan',
  ly: 'libya',
  lby: 'libya',
  tn: 'tunisia',
  tun: 'tunisia',
  sa: 'saudiarabia',
  sau: 'saudiarabia',
  tr: 'turkey',
  tur: 'turkey',
  il: 'israel',
  isr: 'israel',
  jo: 'jordan',
  jor: 'jordan',
  lb: 'lebanon',
  lbn: 'lebanon',
  iq: 'iraq',
  irq: 'iraq',
  ir: 'iran',
  irn: 'iran',
  pk: 'pakistan',
  pak: 'pakistan',
  bd: 'bangladesh',
  bgd: 'bangladesh',
  lk: 'srilanka',
  lka: 'srilanka',
  np: 'nepal',
  npl: 'nepal',
  th: 'thailand',
  tha: 'thailand',
  vn: 'vietnam',
  vnm: 'vietnam',
  ph: 'philippines',
  phl: 'philippines',
  my: 'malaysia',
  mys: 'malaysia',
  id: 'indonesia',
  idn: 'indonesia',
  kr: 'southkorea',
  kp: 'northkorea',
  tw: 'taiwan',
  twn: 'taiwan',
  ru: 'russia',
  rus: 'russia',
  ua: 'ukraine',
  ukr: 'ukraine',
  ro: 'romania',
  rou: 'romania',
  bg: 'bulgaria',
  bgr: 'bulgaria',
  hu: 'hungary',
  hun: 'hungary',
  sk: 'slovakia',
  svk: 'slovakia',
  hr: 'croatia',
  hrv: 'croatia',
  rs: 'serbia',
  srb: 'serbia',
  si: 'slovenia',
  svn: 'slovenia',
  ar: 'argentina',
  arg: 'argentina',
  cl: 'chile',
  chl: 'chile',
  co: 'colombia',
  col: 'colombia',
  pe: 'peru',
  per: 'peru',
  ve: 'venezuela',
  ven: 'venezuela',
  bo: 'bolivia',
  bol: 'bolivia',
  ec: 'ecuador',
  ecu: 'ecuador',
  py: 'paraguay',
  pry: 'paraguay',
  uy: 'uruguay',
  ury: 'uruguay',
  cu: 'cuba',
  cub: 'cuba',
  gt: 'guatemala',
  gtm: 'guatemala',
  hn: 'honduras',
  hnd: 'honduras',
  ni: 'nicaragua',
  nic: 'nicaragua',
  cr: 'costarica',
  cri: 'costarica',
  pa: 'panama',
  pan: 'panama',
};

/**
 * Resolve a location string against an index of normalized feature names.
 * Exact (after aliasing) wins; otherwise a unique prefix match either way
 * (handles "United States" ⊂ "United States of America" and NE abbreviations).
 */
export function matchCountryKey(index: ReadonlySet<string>, location: string): string | null {
  const raw = normalizeCountryKey(location);
  if (!raw) return null;
  const q = COUNTRY_ALIASES[raw] ?? raw;
  if (index.has(q)) return q;
  let found: string | null = null;
  for (const key of index) {
    if (key.startsWith(q) || q.startsWith(key)) {
      if (found && found !== key) return null; // ambiguous
      found = key;
    }
  }
  return found;
}
